apiVersion: 1

datasources:
  - name: InfluxDB_Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: cisco-ai-fabric
      defaultBucket: network_telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: supersecret-token-lab5-telemetry-2026
    editable: true
